### ISSUE TITLE
Sip Diagnostics Intermitente

### ISSUE THREAD

**Issue by Agibert** [pjefika/acs#2]
Intermitência ao obter informações do sip, ocorre erro "Erro ao realizar Sip Diagnostics"

**Comment by Agibert** [comment]
19:53:39,811 ERROR [stderr] (default task-17) java.lang.NullPointerException

19:53:39,813 ERROR [stderr] (default task-17) 	at controllers.comandos.SipDiagnostics.sipDiagnostics(SipDiagnostics.java:55)

19:53:39,813 ERROR [stderr] (default task-17) 	at controllers.comandos.SipDiagnostics.sipDiagnostics(SipDiagnostics.java:85)

**Comment by henmerlin** [comment]
Corrigido via refatoramento das DAOs
